version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-net
    depends_on:
      - db-order
    ports:
      - "9001:9000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-order
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # ✅ ini benar!
    depends_on:
      - app
    networks:
      - laravel-net

  hasura-order:
    image: hasura/graphql-engine:v2.34.0
    ports:
      - "8085:8080" # GUNAKAN PORT BERBEDA AGAR TIDAK BENTROK
    restart: always
    depends_on:
      - db-order
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:admin123@db-order:5432/motor_wash_order_service
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecret-order
    networks:
      - laravel-net

  db-order:
    image: postgres:17
    container_name: db-order
    restart: unless-stopped
    environment:
      POSTGRES_DB: motor_wash_order_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-net
    ports:
      - "5433:5432"

volumes:
  pgdata:


networks:
  laravel-net:
    external: true
